#!/usr/bin/env ruby
STDOUT.sync = true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), *%w(.. lib))

trap("SIGINT") { exit! }

require 'genebrand'
require 'mercenary'

Mercenary.program(:genebrand) do |p|
  p.version Genebrand::VERSION
  p.description 'Genebrand is a small brands generator'
  p.syntax 'genebrand <subcommand> [options]'

  Genebrand::Command.subclasses.each { |c| c.load_command(p) }
end
