#!/usr/bin/env ruby
STDOUT.sync = true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), *%w(.. lib))

require 'genebrand'
require 'mercenary'

Mercenary.program(:genebrand) do |p|
  p.version Genebrand::VERSION
  p.description 'Genebrand is a small brands generator'
  p.syntax 'genebrand <subcommand> [options]'

  p.action do |args, _options|
    if args.empty?
      Genebrand::Logger.error 'A subcommand is required. Use --help for more information'
      abort
    else
      unless p.has_command?(args.first)
        Genebrand::Logger.hint 'Invalid command. Use --help for more information'
        abort
      end
    end
  end

  Genebrand::Command.subclasses.each { |c| c.load_command(p) }
end
